require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


target 'pedalcheckA' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'pedalcheckATests' do
    inherit! :complete
    # Pods for testing
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({'Flipper-Folly' => '2.6'})
  # use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     if ['RNFBApp', 'RNFBMessaging'].include?(target.name)
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
  #       end
  #     if ['RNFBCrashlytics'].include?(target.name)
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
  #       end
  #   end
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
